apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
spec:
  replicas: 1 
  selector:
    matchLabels:
      name: nodeapp
      version: blue
  template:
    metadata:
      labels:
        name: nodeapp
        version: blue
    spec:
      containers:
      - name: nodeapp
        image: tanyastephens/udacity-capstone-blue
        ports:
        - containerPort: 3000
