apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nodeapp-blue
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: nodeapp
        version: blue
    spec:
      containers: 
        - name: nodeapp
          image: tanyastephens/udacity-capstone-blue
          ports:
            - name: http
              containerPort: 3000
