apiVersion: v1
kind: Service
metadata:
  name: green
  app: green
  labels:
    name: green
    app: green
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    name: green
    app: green
  type: LoadBalancer 
