apiVersion: v1
kind: Service
metadata:
  name: bluegreenlb
  labels:
    name: bluegreenlb
spec:
  selector:
    name: bluegreenlb
    app: green
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer 