apiVersion: v1
kind: Service
metadata:
  name: green-deployment
  labels:
    app: green
spec:
  selector:
    name: green-deployment
    app: green
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer