apiVersion: v1
kind: Service
metadata:
  name: nodeapp
  labels:
    name: nodeapp
spec:
  selector:
    name: nodeapp
    version: blue
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer 
