apiVersion: v1
kind: Service
metadata:
  name: green
  labels:
    app: green
spec:
  selector:
    app: green
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer 