apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
  labels:
    name: blue-deployment
    app: blue
spec:
  replicas: 1 
  selector:
    matchLabels:
      name: blue-deployment
      app: blue
  template:
    metadata:
      labels:
        name: blue-deployment
        app: blue
    spec:
      containers:
      - name: blue
        image: tanyastephens/udacity-capstone-blue
        ports:
        - containerPort: 3000