apiVersion: v1
kind: Deployment
metadata:
  name: nodeapp-blue
spec:
  replicas: 1 
  selector:
  template:
    metadata:
      labels:
        name: nodeapp
        version: "blue"
    spec:
      containers:
      - name: nodeapp
        image: tanyastephens/udacity-capstone-blue
        ports:
        - containerPort: 3000      
