apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nodeapp-green
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: nodeapp
        version: "green"
    spec:
      containers: 
        - name: nodeapp
          image: tanyastephens/udacity-capstone-green
          ports:
            - name: http
              containerPort: 3000