apiVersion: v1
kind: Service
metadata: 
  name: nodeapp
  labels: 
    name: nodeapp
spec:
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector: 
    name: nodeapp
    version: blue
  type: LoadBalancer
