pipeline {
   agent any
   environment {
       registry = "tanyawms/udccapstone"
   }
   stages {
       stage('Build') {
           steps {
               // Create the node app 
               sh 'run_docker.sh'
           }    
       }
       stage('Publish') {
           steps {
               // Upload to Dockerhub 
               sh 'upload_docker.sh'
           } 
       }
   }
}
