pipeline {
  agent any
    
  tools {nodejs "node"}
    
  stages {
        
    stage('Cloning Git') {
      steps {
        git 'https://github.com/tanyawms/udccapstone'
      }
    }
    stage('Create directories') {
      steps {
        sh '''
            mkdir -p /var/lib/jenkins/node/app/node_modules
            cp /var/lib/jenkins/workspace/create-node-app/blue/package*.json /var/lib/jenkins/node/app/
            mkdir -p /var/lib/jenkins/node/app/test
            cp -r /var/lib/jenkins/workspace/create-node-app/blue/test /var/lib/jenkins/node/app/
            mkdir -p /var/lib/jenkins/node/app/views
            cp -r /var/lib/jenkins/workspace/create-node-app/blue/views /var/lib/jenkins/node/app/
        '''
      }
    }
    stage('Install dependencies') {
      steps {
        sh 'npm install'
      }
    }
    stage('Test') {
      steps {
         sh '/var/lib/jenkins/node/app/node_modules/.bin/mocha /var/lib/jenkins/node/app/test/test.js'
      }
    }      
  }
}
